branches: ["main"]
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      releaseRules:
        - type: refactor
          release: patch
        # Override default rules for pre-1.0
        - breaking: true
          release: minor
        - type: feat
          release: patch
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
  - "@semantic-release/release-notes-generator"
  - - "semantic-release-replace-plugin"
    - replacements:
        - files: ["Cargo.toml", "Cargo.lock"]
          from: "name = \"senc\"\nversion = \".*\""
          to: "name = \"senc\"\nversion = \"${nextRelease.version}\""
          countMatches: true
          results:
            - file: "Cargo.toml"
              hasChanged: true
              numMatches: 1
              numReplacements: 1
            - file: "Cargo.lock"
              hasChanged: true
              numMatches: 1
              numReplacements: 1
  - - "@semantic-release/git"
    - assets: ["Cargo.toml", "Cargo.lock"]
      message: "release: ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - - "@semantic-release/github"
    - assets: ["/tmp/artifact/*"]
