branches: ["release"]
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      releaseRules:
        - type: refactor
          release: patch
        - type: chore
          release: patch
        # Override default rules for pre-1.0
        - breaking: true
          release: minor
        - type: feat
          release: patch
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: Features
          - type: fix
            section: Bug fixes
          - type: chore
            section: Other updates
  - - "semantic-release-replace-plugin"
    - replacements:
        - files: ["Cargo.toml", "Cargo.lock"]
          from: "name = \"senc\"\nversion = \".*\""
          to: "name = \"senc\"\nversion = \"${nextRelease.version}\""
          countMatches: true
          results:
            - file: "Cargo.toml"
              hasChanged: true
              numMatches: 1
              numReplacements: 1
            - file: "Cargo.lock"
              hasChanged: true
              numMatches: 1
              numReplacements: 1
  - - "@semantic-release/npm"
    - npmPublish: true
      pkgRoot: "./packages/types"
  - - "@semantic-release/git"
    - assets:
        - "Cargo.toml"
        - "Cargo.lock"
        - "./packages/types/package.json"
        - "./packages/types/npm-shrinkwrap.json"
      message: "release: ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - - "@semantic-release/github"
    - assets: ["/tmp/artifact/*"]
